### ISSUE TITLE
XSpec Add-on not compatible with oXygen 26 (?)

### ISSUE THREAD

**Issue by o-sapov** [xspec/xspec#1810]
After upgrading to <oXygen/> XML Editor 26.0, build 2023100905 I cannot run XSpec Add-on (2.2.6).

Error:

```
Executing:
"c:\users\sapov\appdata\local\programs\oxygen xml editor 26\jre/bin/java" -Dfile.encoding=UTF-8 -Xmx256m -Djava.awt.headless=true -Dsun.io.useCanonCaches=true -classpath "C:\Users\sapov\AppData\Local\Programs\Oxygen XML Editor 26\tools\ant/lib/ant-launcher.jar" "-Dant.home=C:\Users\sapov\AppData\Local\Programs\Oxygen XML Editor 26\tools\ant" org.apache.tools.ant.launch.Launcher -lib "C:\Users\sapov\AppData\Local\Programs\Oxygen XML Editor 26\classes" -lib "C:\Users\sapov\AppData\Local\Programs\Oxygen XML Editor 26\lib\oxygenCommons.jar" -lib "C:\Users\sapov\AppData\Local\Programs\Oxygen XML Editor 26\lib\oxygen.jar" -lib "C:\Users\sapov\AppData\Local\Programs\Oxygen XML Editor 26\lib\oxygenDeveloper.jar" -lib "C:\Users\sapov\AppData\Local\Programs\Oxygen XML Editor 26\lib\oxygenEclipse.jar" -lib "C:\Users\sapov\AppData\Local\Programs\Oxygen XML Editor 26\lib\oxygenDeveloperEclipse.jar" -lib "C:\Users\sapov\AppData\Local\Programs\Oxygen XML Editor 26\lib\oxygen-sandbox.jar" -lib "C:\Users\sapov\AppData\Local\Programs\Oxygen XML Editor 26\lib\oxygen-license.jar" -lib "C:\Users\sapov\AppData\Local\Programs\Oxygen XML Editor 26\lib\oxygen-basic-utilities.jar" -lib "C:\Users\sapov\AppData\Local\Programs\Oxygen XML Editor 26\lib\oxygen-editor-variables-parser.jar" -lib "C:\Users\sapov\AppData\Local\Programs\Oxygen XML Editor 26\lib\xml-apis.jar" -lib "C:\Users\sapov\AppData\Local\Programs\Oxygen XML Editor 26\lib\oxygen-patched-resolver.jar" -lib "C:\Users\sapov\AppData\Local\Programs\Oxygen XML Editor 26\lib\xmlresolver-5.2.1.jar" -lib "C:\Users\sapov\AppData\Local\Programs\Oxygen XML Editor 26\lib\xmlresolver-5.2.1.jar" -lib "C:\Users\sapov\AppData\Local\Programs\Oxygen XML Editor 26\lib\oxygen-patched-slf4j.jar" -lib "C:\Users\sapov\AppData\Local\Programs\Oxygen XML Editor 26\lib\logback-classic-1.2.10.jar" -lib "C:\Users\sapov\AppData\Local\Programs\Oxygen XML Editor 26\lib\logback-core-1.2.10.jar" -lib "C:\Users\sapov\AppData\Local\Programs\Oxygen XML Editor 26\lib\log4j-over-slf4j-1.7.32.jar" -lib "C:\Users\sapov\AppData\Local\Programs\Oxygen XML Editor 26\lib\log4j-to-slf4j-2.17.1.jar" -lib "C:\Users\sapov\AppData\Local\Programs\Oxygen XML Editor 26\lib\log4j-api-2.17.1.jar" -lib "C:\Users\sapov\AppData\Local\Programs\Oxygen XML Editor 26\lib\log4j.jar" -lib "C:\Users\sapov\AppData\Local\Programs\Oxygen XML Editor 26\lib\oxygen-patched-xerces.jar" -lib "C:\Users\sapov\AppData\Local\Programs\Oxygen XML Editor 26\lib\guava-32.0.1-jre.jar" -lib "C:\Users\sapov\AppData\Roaming\com.oxygenxml\extensions\v26.0\frameworks\com.oxygenxml.xspec.XSpecSupportFramework\xspec.support-2.2.6\oxygen-results-view\saxon-extension.jar" -f "build.xml" "-Dcatalog=file:/C:/Users/sapov/AppData/Local/Programs/Oxygen%20XML%20Editor%2026/frameworks/dita/catalog.xml;file:/C:/Users/sapov/AppData/Local/Programs/Oxygen%20XML%20Editor%2026/frameworks/dita/DITA-OT/catalog-dita.xml;file:/C:/Users/sapov/AppData/Local/Programs/Oxygen%20XML%20Editor%2026/frameworks/dita/styleguide/catalog.xml;file:/C:/Users/sapov/AppData/Local/Programs/Oxygen%20XML%20Editor%2026/frameworks/dita/plugin/catalog.xml;file:/C:/Users/sapov/AppData/Local/Programs/Oxygen%20XML%20Editor%2026/frameworks/dita/catalog.xml;file:/C:/Users/sapov/AppData/Local/Programs/Oxygen%20XML%20Editor%2026/frameworks/dita/catalog.xml;file:/C:/Users/sapov/AppData/Local/Programs/Oxygen%20XML%20Editor%2026/frameworks/dita/styleguide/catalog.xml;file:/C:/Users/sapov/AppData/Local/Programs/Oxygen%20XML%20Editor%2026/frameworks/dita/plugin/catalog.xml;file:/C:/Users/sapov/AppData/Local/Programs/Oxygen%20XML%20Editor%2026/frameworks/daisy/catalog.xml;file:/C:/Users/sapov/AppData/Local/Programs/Oxygen%20XML%20Editor%2026/frameworks/docbook/catalog.xml;file:/C:/Users/sapov/AppData/Local/Programs/Oxygen%20XML%20Editor%2026/frameworks/docbook/5.0/catalog.xml;file:/C:/Users/sapov/AppData/Local/Programs/Oxygen%20XML%20Editor%2026/frameworks/docbook/5.1/catalog.xml;file:/C:/Users/sapov/AppData/Local/Programs/Oxygen%20XML%20Editor%2026/frameworks/ead/catalog.xml;file:/C:/Users/sapov/AppData/Local/Programs/Oxygen%20XML%20Editor%2026/frameworks/jats/lib/schemas/jatskit-catalog.xml;file:/C:/Users/sapov/AppData/Local/Programs/Oxygen%20XML%20Editor%2026/frameworks/kml/schema/catalog.xml;file:/C:/Users/sapov/AppData/Local/Programs/Oxygen%20XML%20Editor%2026/frameworks/mathml/catalog.xml;file:/C:/Users/sapov/AppData/Local/Programs/Oxygen%20XML%20Editor%2026/frameworks/maven/catalog.xml;file:/C:/Users/sapov/AppData/Local/Programs/Oxygen%20XML%20Editor%2026/frameworks/ncx/catalog.xml;file:/C:/Users/sapov/AppData/Local/Programs/Oxygen%20XML%20Editor%2026/frameworks/svg/dtd/svgcatalog.xml;file:/C:/Users/sapov/AppData/Local/Programs/Oxygen%20XML%20Editor%2026/frameworks/stratml/part1/xsd/catalog.xml;file:/C:/Users/sapov/AppData/Local/Programs/Oxygen%20XML%20Editor%2026/frameworks/stratml/part2/xsd/catalog.xml;file:/C:/Users/sapov/AppData/Local/Programs/Oxygen%20XML%20Editor%2026/frameworks/tei/xml/tei/custom/schema/catalog.xml;file:/C:/Users/sapov/AppData/Local/Programs/Oxygen%20XML%20Editor%2026/frameworks/tei/xml/tei/schema/catalog.xml;file:/C:/Users/sapov/AppData/Local/Programs/Oxygen%20XML%20Editor%2026/frameworks/tei/xml/tei/stylesheet/catalog.xml;file:/C:/Users/sapov/AppData/Local/Programs/Oxygen%20XML%20Editor%2026/frameworks/wsdl/wsdlcatalog.xml;file:/C:/Users/sapov/AppData/Local/Programs/Oxygen%20XML%20Editor%2026/frameworks/xhtml/dtd/xhtmlcatalog.xml;file:/C:/Users/sapov/AppData/Local/Programs/Oxygen%20XML%20Editor%2026/frameworks/xhtml/relaxng/catalog.xml;file:/C:/Users/sapov/AppData/Local/Programs/Oxygen%20XML%20Editor%2026/frameworks/xhtml/nvdl/catalog.xml;file:/C:/Users/sapov/AppData/Local/Programs/Oxygen%20XML%20Editor%2026/frameworks/xhtml11/dtd/xhtmlcatalog.xml;file:/C:/Users/sapov/AppData/Local/Programs/Oxygen%20XML%20Editor%2026/frameworks/xhtml11/schema/xhtmlcatalog.xml;file:/C:/Users/sapov/AppData/Local/Programs/Oxygen%20XML%20Editor%2026/frameworks/xhtml/xhtml5%20(epub3)/catalog-compat.xml;file:/C:/Users/sapov/AppData/Local/Programs/Oxygen%20XML%20Editor%2026/frameworks/xhtml/styleguide/catalog.xml;file:/C:/Users/sapov/AppData/Local/Programs/Oxygen%20XML%20Editor%2026/frameworks/xliff/schemas/1.2/catalog.xml;file:/C:/Users/sapov/AppData/Local/Programs/Oxygen%20XML%20Editor%2026/frameworks/xliff/schemas/2.0/catalog.xml;file:/C:/Users/sapov/AppData/Local/Programs/Oxygen%20XML%20Editor%2026/frameworks/xliff/schemas/2.1/catalog.xml;file:/C:/Users/sapov/AppData/Local/Programs/Oxygen%20XML%20Editor%2026/frameworks/xmlschema/catalog.xml;file:/C:/Users/sapov/AppData/Local/Programs/Oxygen%20XML%20Editor%2026/frameworks/xmlspec/catalog.xml;file:/C:/Users/sapov/AppData/Local/Programs/Oxygen%20XML%20Editor%2026/frameworks/focheck/schema/catalog.xml;file:/C:/Users/sapov/AppData/Local/Programs/Oxygen%20XML%20Editor%2026/frameworks/fo/xsd/catalog.xml;file:/C:/Users/sapov/AppData/Local/Programs/Oxygen%20XML%20Editor%2026/frameworks/catalog.xml" "-Dcatalog.is.uri=true" "-Dclean.output.dir=false" "-Dxspec.xquery.compiler.xsl=C:/Users/sapov/AppData/Roaming/com.oxygenxml/extensions/v26.0/frameworks/com.oxygenxml.xspec.XSpecSupportFramework/xspec.support-2.2.6/oxygen-results-view/compile-xquery-tests-oxygen.xsl" "-Dxspec.xslt.compiler.xsl=C:/Users/sapov/AppData/Roaming/com.oxygenxml/extensions/v26.0/frameworks/com.oxygenxml.xspec.XSpecSupportFramework/xspec.support-2.2.6/oxygen-results-view/compile-xslt-tests-oxygen.xsl" "-Dxspec.compiler.saxon.config=C:/Users/sapov/AppData/Roaming/com.oxygenxml/extensions/v26.0/frameworks/com.oxygenxml.xspec.XSpecSupportFramework/xspec.support-2.2.6/oxygen-results-view/saxon-config.xml" "-Dtest.type=t" "-Dxspec.fail=false" "-Dxspec.html.reporter.xsl=C:/Users/sapov/AppData/Roaming/com.oxygenxml/extensions/v26.0/frameworks/com.oxygenxml.xspec.XSpecSupportFramework/xspec.support-2.2.6/oxygen-results-view/unit-report-oxygen.xsl" "-Dxspec.project.dir=C:/Users/sapov/AppData/Roaming/com.oxygenxml/extensions/v26.0/frameworks/com.oxygenxml.xspec.XSpecSupportFramework/xspec.support-2.2.6/" "-Dxspec.result.html=C:\Users\sapov\Documents\dime-mei-tools\util\transformation\extract-parts\tests/main-report.html" "-Dxspec.force.focus=" "-Dxspec.xml=C:\Users\sapov\Documents\dime-mei-tools\util\transformation\extract-parts\tests\main.xspec" "-Dwebhelp.trial.license=no"

Buildfile: C:\Users\sapov\AppData\Roaming\com.oxygenxml\extensions\v26.0\frameworks\com.oxygenxml.xspec.XSpecSupportFramework\xspec.support-2.2.6\build.xml

init:
     [echo] Testing main.xspec [t]

generate-catalog:
     [xslt] Processing C:\Users\sapov\AppData\Roaming\com.oxygenxml\extensions\v26.0\frameworks\com.oxygenxml.xspec.XSpecSupportFramework\xspec.support-2.2.6\build.xml to C:\Users\sapov\Documents\dime-mei-tools\util\transformation\extract-parts\tests\xspec\main_catalog.xml
     [xslt] Loading stylesheet C:\Users\sapov\AppData\Roaming\com.oxygenxml\extensions\v26.0\frameworks\com.oxygenxml.xspec.XSpecSupportFramework\xspec.support-2.2.6\src\ant\generate-catalog.xsl
     [xslt] Failed to load net.sf.saxon.TransformerFactoryImpl via the configured classpath, will try Ant's classpath instead.
     [xslt] Failed to process C:\Users\sapov\AppData\Roaming\com.oxygenxml\extensions\v26.0\frameworks\com.oxygenxml.xspec.XSpecSupportFramework\xspec.support-2.2.6\build.xml

BUILD FAILED
C:\Users\sapov\AppData\Roaming\com.oxygenxml\extensions\v26.0\frameworks\com.oxygenxml.xspec.XSpecSupportFramework\xspec.support-2.2.6\build.xml:289: The following error occurred while executing this line:
C:\Users\sapov\AppData\Roaming\com.oxygenxml\extensions\v26.0\frameworks\com.oxygenxml.xspec.XSpecSupportFramework\xspec.support-2.2.6\build.xml:196: java.lang.ClassNotFoundException: net.sf.saxon.TransformerFactoryImpl
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at org.apache.tools.ant.taskdefs.optional.TraXLiaison.getFactory(TraXLiaison.java:401)
	at org.apache.tools.ant.taskdefs.optional.TraXLiaison.getSource(TraXLiaison.java:247)
	at org.apache.tools.ant.taskdefs.optional.TraXLiaison.readTemplates(TraXLiaison.java:297)
	at org.apache.tools.ant.taskdefs.optional.TraXLiaison.createTransformer(TraXLiaison.java:311)
	at org.apache.tools.ant.taskdefs.optional.TraXLiaison.transform(TraXLiaison.java:187)
	at org.apache.tools.ant.taskdefs.XSLTProcess.process(XSLTProcess.java:870)
	at org.apache.tools.ant.taskdefs.XSLTProcess.execute(XSLTProcess.java:408)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at java.base/java.util.Vector.forEach(Vector.java:1365)
	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:67)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:391)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at org.apache.tools.ant.Target.execute(Target.java:449)
	at org.apache.tools.ant.Target.performTasks(Target.java:470)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1374)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
	at org.apache.tools.ant.Main.runBuild(Main.java:827)
	at org.apache.tools.ant.Main.startAnt(Main.java:223)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)

Total time: 0 seconds

The process finished with exit code: 1
```
Cp. my post on oXygen Forum

https://www.oxygenxml.com/forum/common-problems/topic26285.html

I can run the same file with oXygen 25.1 version.

**Comment by AirQuick** [comment]
I believe xspec/oXygen-XML-editor-xspec-support#51 will resolve it.

**Comment by AirQuick** [comment]
Ah, no. Will need another change.

**Comment by AirQuick** [comment]
Opened xspec/oXygen-XML-editor-xspec-support#52
